
-- 3 --

SELECT 
  U.ORIENTACION,
  AVG(M.TIEMPO_ENTRE_LIKES) AS PROMEDIO_TIEMPO_ORIENTACION,
  RANK() OVER (ORDER BY AVG(M.TIEMPO_ENTRE_LIKES) ASC) AS RANK_ORIENTACION
FROM MATCHES M 
JOIN USUARIO U ON M.COD_U1 = U.COD
GROUP BY U.ORIENTACION;