
--BRIDGE--

INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (-1, 'sin_interes', 1.0);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (1, 'cine', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (1, 'musica', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (1, 'podcasts', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (2, 'futbol', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (2, 'cine', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (2, 'baloncesto', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (3, 'viajes', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (3, 'tecnologia', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (3, 'blockchain', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (4, 'anime', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (4, 'videojuegos', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (4, 'k-pop', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (5, 'musica', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (5, 'literatura', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (5, 'jazz', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (6, 'fotografia', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (6, 'moda', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (6, 'skate', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (7, 'cine', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (7, 'comics', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (7, 'peliculas indie', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (8, 'cocina', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (8, 'reposteria', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (9, 'videojuegos', 1);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (10, 'moda', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (10, 'futbol', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (10, 'decoracion', 0.3333);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (11, 'filosofia', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (11, 'psicologia', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (12, 'historia', 1);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (13, 'yoga', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (13, 'naturaleza', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (14, 'viajes', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (14, 'cocina', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (15, 'tecnologia', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (15, 'cine', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (16, 'programacion', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (16, 'filosofia', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (17, 'ajedrez', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (17, 'robotica', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (18, 'viajes', 1);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (19, 'pintura', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (19, 'arte', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (20, 'meditacion', 0.5);
INSERT INTO Bridge (id_grupo, id_interes, peso) VALUES (20, 'tai chi', 0.5);
